modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/wireless_redstone/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "wireless_redstone"
version = "${version}"
displayName = "Wireless Redstone"
authors = "MrMelon54"
description = "${description}"
logoFile = "/icon.png"

[[dependencies.wireless_redstone]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.wireless_redstone]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "NONE"
side = "BOTH"
