modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/MrMelon54/wireless_redstone/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "wireless_redstone"
version = "${version}"
displayName = "Wireless Redstone"
authors = "MrMelon54"
description = "Wireless Redstone, what more can I say?"
logoFile = "/icon.png"

[[dependencies.wireless_redstone]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wireless_redstone]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wireless_redstone]]
modId = "architectury"
mandatory = true
versionRange = "[9.0.0,)"
ordering = "AFTER"
side = "BOTH"
