modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/mrmelon54/wireless_redstone/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "wireless_redstone"
version = "${version}"
displayName = "Wireless Redstone"
authors = "MrMelon54"
description = "${description}"
logoFile = "icon.png"
displayURL = "https://mrmelon54.com/minecraft/wireless-redstone"

[[dependencies.wireless_redstone]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_minecraft_versions}"
ordering = "NONE"
side = "BOTH"

[[dependencies.wireless_redstone]]
modId = "infrastructury"
mandatory = true
versionRange = "[${infrastructury_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wireless_redstone]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"
